# [Team Project] Yes24 홈페이지 가상 리뉴얼
## 💙프로젝트 소개
### Team Member
- 이상아
- 김지혜
- 백승우
- 선수민
- 안재혁
- 장진수
### 프로젝트 목표
YES24 홈페이지의 회원가입, 로그인, 로그아웃, 게시판 CRUD 기능 구현
### 사용 프로그램
- 서버환경 : tomcat 9.0
- JSP : 2.3 / servlet3.1 / JDK 1.8.0
- 언어 : Java, JavaScript
- DB : Oracle 11g (로컬)
- O/S : Windows
- Tool : Eclipse
### 정보 구조 설계
<p align=center><img width="80%" src="https://github.com/sangah97/sangah97.github.io/blob/main/yes24_diagram.png"></p>

### DB 설계
<p align=center><img width="80%" src="https://github.com/sangah97/sangah97.github.io/blob/main/yes24_erd.png"></p>
<br><br>

## 💙기능소개
### 로그인
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313909597-7d6842c0-3195-480a-b2fa-559640655c44.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjAyNzIsIm5iZiI6MTcxMDgxOTk3MiwicGF0aCI6Ii8yNTkxNTExMC8zMTM5MDk1OTctN2Q2ODQyYzAtMzE5NS00ODBhLWIyZmEtNTU5NjQwNjU1YzQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyM2E1OWI3MmNiNzU2OGE5ZWI5M2FlYjQ1NTUyZTgzOGJiOTVlNzQxODMxMjdiOTNiMTA1MjM3OWUyOGFmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4hxUlnLp0wkMzOFMriHNHqmIt7MQ6NY6EMVZyTU54Y"></p> 

#### - 로그인 실패
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313945298-a68d27d7-16fe-4bd9-b0c8-e76cef44ed41.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjk5ODgsIm5iZiI6MTcxMDgyOTY4OCwicGF0aCI6Ii8yNTkxNTExMC8zMTM5NDUyOTgtYTY4ZDI3ZDctMTZmZS00YmQ5LWIwYzgtZTc2Y2VmNDRlZDQxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZmY2NWFlY2NmYmE4OTg2YmEyMzE2ODIxZmZiMDgyZTc4NjllMTA4MGU3YTc1NzA2YjU1NzU1NWE3MzZmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tz_F9vcb9V77fUGf_YVR40ZC79AvICwtrXCmJYrYOZs"></p>

#### - 로그인 성공
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313945375-dc235604-7c82-4459-9dc4-6f18e939c377.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzAwNDcsIm5iZiI6MTcxMDgyOTc0NywicGF0aCI6Ii8yNTkxNTExMC8zMTM5NDUzNzUtZGMyMzU2MDQtN2M4Mi00NDU5LTlkYzQtNmYxOGU5MzljMzc3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MjkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWU2ZDRiOGVhNTY3MGNlZGFlZmYwODlkY2Q0YTI5ZGI3YjAyMGUxZTM1NDhkMTFiYzQ4NDkwYzE4ZDMxMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huhODW6IIduIiG-CjLTsUZOpbmnDB77cd2L_HvWTKk4"></p>
<br><br>

---
<br><br>

### 회원가입
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313913098-62fb92fe-a22d-4e1f-ab4b-f79b2673e3b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjA2NTYsIm5iZiI6MTcxMDgyMDM1NiwicGF0aCI6Ii8yNTkxNTExMC8zMTM5MTMwOTgtNjJmYjkyZmUtYTIyZC00ZTFmLWFiNGItZjc5YjI2NzNlM2IxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTgxNWI2NDI4ZmU1YzA5MjkzNjE3ODcwMDZmMWFlM2U5MzUzZmJjZDQ0NjMxMDBiYTM1YWQwN2RkY2RhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cTVaZCCLFsk2uHMd7_bq19aRG1-tnurUmigG6NsPENg"></p>

#### - 회원가입 실패
<p align=center><img width="70%" src="https://raw.githubusercontent.com/sangah97/sangah97.github.io/main/join_err.png"></p>

#### - 회원가입 성공
<p align=center><img width="70%" src="https://raw.githubusercontent.com/sangah97/sangah97.github.io/main/join_succ.png"></p>
<br><br>

---
<br><br>

### 1:1문의
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313925571-e8b9db86-1bd0-46d9-bd08-cf6f9fb1c962.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjQ1MzUsIm5iZiI6MTcxMDgyNDIzNSwicGF0aCI6Ii8yNTkxNTExMC8zMTM5MjU1NzEtZThiOWRiODYtMWJkMC00NmQ5LWJkMDgtY2Y2ZjlmYjFjOTYyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA0NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2RjOWM3MzY0ZmFjZjZmMTVlNmNjMWFlYzcwMzM3OWQ3Y2IyNWM1YjdhYzE5YzgxNmEzYTdkYzk1ZjYzZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRuL3C_XF3KjXw9GUlgfvSV3DTtU3b5RbIeviTp4RM8"></p>

#### - 문의 작성
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313956556-68fd908c-2c03-4423-b4d5-06c4c9aff081.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzI3MzIsIm5iZiI6MTcxMDgzMjQzMiwicGF0aCI6Ii8yNTkxNTExMC8zMTM5NTY1NTYtNjhmZDkwOGMtMmMwMy00NDIzLWI0ZDUtMDZjNGM5YWZmMDgxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzA2OGQ3ZmViMzAzYTljNmEyYmUzNjU3ZjNhYTAwMzY2NzVkZTJmMWY0OTQ5NDQ4ODlkMGNmNzgxNmYxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WX4Pexqaz6gfVoe2Vj8Pry1QW8g65gKnK8lUrPEbONM"></p>

#### - 문의 수정
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313956445-a31592fb-7239-43de-aa06-2085a7d9a174.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzI3NjMsIm5iZiI6MTcxMDgzMjQ2MywicGF0aCI6Ii8yNTkxNTExMC8zMTM5NTY0NDUtYTMxNTkyZmItNzIzOS00M2RlLWFhMDYtMjA4NWE3ZDlhMTc0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNTU4ODNhZGVkM2JkYTMyYWRkNjliYjRmNTkyYzAyMzQwMzA0NjE2YWY4ZjE2ZGQ2ZjgxZDAxN2Y4NzM2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jHUH0-POhCyJ_a4uUQWhvJJC3YTvZmSKrcqt9kscv5w"></p>

#### - 문의 삭제
<p align=center><img width="70%" src="https://private-user-images.githubusercontent.com/25915110/313956275-ff308d86-6b8e-48f4-936f-1476d3969be5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzI3NzcsIm5iZiI6MTcxMDgzMjQ3NywicGF0aCI6Ii8yNTkxNTExMC8zMTM5NTYyNzUtZmYzMDhkODYtNmI4ZS00OGY0LTkzNmYtMTQ3NmQzOTY5YmU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA3MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYTlkYTU2MTZjNDk2NDczOGJiNTE2MzI3MGY0NDYxYjA3ZjY4Yjc0MzVjNTlkYTQ1ZjE2MDA1NDc4OTVlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPXHNcvZGPHQjITeTQMS3VEhUum4DS25CBr0hv4_Nng"></p>
<br><br>

---
<br><br>

<br><br>
## 💙기능소개 .mp4
https://github.com/sangah97/sangah97/assets/25915110/0139e22a-1114-404e-adbc-4880aecac997
